block-beta
columns 1
  db(("User"))
  blockArrowId6<["&nbsp;&nbsp;&nbsp;"]>(down)
  block:ID
    B["Create new note at Note Single app"]
    A["URL change to https://studies.cs.helsinki.fi/exampleapp/spa"]
    C["Status Code become 304 and request methode change to get"]
  end
  space
  D
  ID --> D["Data.json, spa.js and main.css are loaded"]
  C --> D
  style B fill:#969,stroke:#333,stroke-width:4px